language: python

python:
  - 3.7

install:
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls

script:
  - coverage run --source=PythonLinearNonlinearControl setup.py pytest

after_success:
  - coveralls